
-- SG SecureBank - 50 clients de test


DROP TABLE fraud CASCADE CONSTRAINTS;
DROP TABLE transactions CASCADE CONSTRAINTS;
DROP TABLE comptes CASCADE CONSTRAINTS;
DROP TABLE clients CASCADE CONSTRAINTS;

CREATE TABLE clients (
    client_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom             VARCHAR2(100)   NOT NULL,
    prenom          VARCHAR2(100)   NOT NULL,
    email           VARCHAR2(150)   UNIQUE NOT NULL,
    mot_de_passe    VARCHAR2(255)   NOT NULL,
    telephone       VARCHAR2(20),
    date_naissance  DATE            NOT NULL,
    adresse         VARCHAR2(255),
    pays            VARCHAR2(100)   DEFAULT 'France',
    date_creation   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    statut          VARCHAR2(20)    DEFAULT 'ACTIF'
                    CHECK (statut IN ('ACTIF', 'SUSPENDU', 'CLOTURE'))
);

CREATE TABLE comptes (
    compte_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       NUMBER          NOT NULL,
    numero_compte   VARCHAR2(34)    UNIQUE NOT NULL,
    type_compte     VARCHAR2(20)    NOT NULL
                    CHECK (type_compte IN ('COURANT', 'EPARGNE', 'PROFESSIONNEL')),
    solde           NUMBER(15, 2)   DEFAULT 0.00,
    devise          VARCHAR2(10)    DEFAULT 'EUR',
    date_ouverture  DATE            DEFAULT SYSDATE,
    statut          VARCHAR2(20)    DEFAULT 'ACTIF'
                    CHECK (statut IN ('ACTIF', 'BLOQUE', 'CLOTURE')),
    CONSTRAINT fk_compte_client FOREIGN KEY (client_id) REFERENCES clients(client_id)
);

CREATE TABLE transactions (
    transaction_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compte_id           NUMBER          NOT NULL,
    type_transaction    VARCHAR2(30)    NOT NULL
                        CHECK (type_transaction IN ('PAIEMENT_EN_LIGNE','VIREMENT','RETRAIT','DEPOT','TRANSACTION_MOBILE')),
    montant             NUMBER(15, 2)   NOT NULL,
    devise              VARCHAR2(10)    DEFAULT 'EUR',
    pays_origine        VARCHAR2(100),
    pays_destination    VARCHAR2(100),
    date_transaction    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    ip_adresse          VARCHAR2(50),
    statut              VARCHAR2(20)    DEFAULT 'EN_ATTENTE'
                        CHECK (statut IN ('EN_ATTENTE','VALIDEE','REJETEE','EN_ANALYSE')),
    score_risque        NUMBER(5, 2)    DEFAULT 0.00,
    CONSTRAINT fk_transaction_compte FOREIGN KEY (compte_id) REFERENCES comptes(compte_id)
);

CREATE TABLE fraud (
    fraud_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id      NUMBER          NOT NULL,
    type_fraude         VARCHAR2(50)
                        CHECK (type_fraude IN ('PHISHING','USURPATION_IDENTITE','TRANSACTION_INHABITUELLE','ACCES_NON_AUTORISE','AUTRE')),
    niveau_risque       VARCHAR2(20)    DEFAULT 'MOYEN'
                        CHECK (niveau_risque IN ('FAIBLE','MOYEN','ELEVE','CRITIQUE')),
    score_ml            NUMBER(5, 2),
    date_detection      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    statut_analyse      VARCHAR2(20)    DEFAULT 'EN_COURS'
                        CHECK (statut_analyse IN ('EN_COURS','CONFIRME','FAUX_POSITIF','RESOLU')),
    analyste_id         VARCHAR2(50),
    commentaire         VARCHAR2(500),
    CONSTRAINT fk_fraud_transaction FOREIGN KEY (transaction_id) REFERENCES transactions(transaction_id)
);

CREATE INDEX idx_transactions_compte ON transactions(compte_id);
CREATE INDEX idx_transactions_date   ON transactions(date_transaction);
CREATE INDEX idx_transactions_statut ON transactions(statut);
CREATE INDEX idx_fraud_transaction   ON fraud(transaction_id);
CREATE INDEX idx_fraud_niveau        ON fraud(niveau_risque);
CREATE INDEX idx_comptes_client      ON comptes(client_id);

-- INSERT clients
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Dupont', 'Marie', 'marie.dupont_1@gmail.com', '$2b$12$i95ZeF', '0686210716', TO_DATE('1964-11-16', 'YYYY-MM-DD'), '19 boulevard Voltaire, Marseille', 'France', 'CLOTURE');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Martin', 'Lucas', 'lucas.martin_2@yahoo.com', '$2b$12$i9', '0638287068', TO_DATE('1977-04-10', 'YYYY-MM-DD'), '83 boulevard Haussmann, Marseille', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Bernard', 'Sara', 'sara.bernard_3@gmail.com', '$2b$12$i95ZeF', '0612509102', TO_DATE('1964-08-09', 'YYYY-MM-DD'), '16 rue du Port, Rennes', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Petit', 'Wei', 'wei.petit_4@yahoo.com', 'zyQ4ZeB2XPyps', '0655819430', TO_DATE('1999-01-11', 'YYYY-MM-DD'), '39 rue de la Paix, Toulouse', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Robert', 'Paul', 'paul.robert_5@gmail.com', 'AFcKozyQ4ZeW', '0645803520', TO_DATE('1961-03-21', 'YYYY-MM-DD'), '29 avenue Montaigne, Nantes', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Richard', 'Emma', 'emma.richard_6@yahoo.com', '$2b$p3Cps3v0Jr4W', '0631640213', TO_DATE('1984-06-19', 'YYYY-MM-DD'), '21 rue de la Paix, Rennes', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Simon', 'Hugo', 'hugo.simon_7@gmail.com', '$2bpEips3Kz4W', '0676397168', TO_DATE('1983-04-08', 'YYYY-MM-DD'), '68 avenue Foch, Nice', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Michel', 'Léa', 'lea.michel_8@yahoo.com', '3KzdfxCv0Jr4W', '0645666014', TO_DATE('1986-02-11', 'YYYY-MM-DD'), '4 rue du Port, Rennes', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Lefebvre', 'Nathan', 'nathan.lefebvre_9@gmail.com', 'B2XPyps3KzdfxCv0Jr4W', '0612233308', TO_DATE('1961-11-17', 'YYYY-MM-DD'), '97 avenue Montaigne, Lille', 'France', 'SUSPENDU');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Leroy', 'Camille', 'camille.leroy_10@yahoo.com', '3CqbXkaTpEipJ.', '0699373036', TO_DATE('1973-08-11', 'YYYY-MM-DD'), '94 boulevard Haussmann, Strasbourg', 'France', 'SUSPENDU');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Moreau', 'Thomas', 'thomas.moreau_11@gmail.com', '$2eB2XPypfxCv0Jr4W', '0652809901', TO_DATE('1963-09-03', 'YYYY-MM-DD'), '72 rue de Rivoli, Marseille', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Laurent', 'Manon', 'manon.laurent_12@yahoo.com', '$2b$12$i93KzdfxCv0Jr4W', '0642126315', TO_DATE('1973-02-13', 'YYYY-MM-DD'), '19 avenue Montaigne, Paris', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Girard', 'Théo', 'theo.girard_13@gmail.com', '$XPyps3KzdfxCv0Jr4W', '0646558691', TO_DATE('1969-02-24', 'YYYY-MM-DD'), '23 avenue Montaigne, Bordeaux', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Bonnet', 'Chloé', 'chloe.bonnet_14@yahoo.com', '$2b$ddgyjkr4W', '0690162505', TO_DATE('1962-04-14', 'YYYY-MM-DD'), '86 rue de Rivoli, Nantes', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Francois', 'Maxime', 'maxime.francois_15@gmail.com', '$2b$dfxCv0Jr4W', '0633348184', TO_DATE('1993-01-18', 'YYYY-MM-DD'), '21 rue de Rivoli, Toulouse', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Legrand', 'Inès', 'ines.legrand_16@yahoo.com', '$2b5zdfxCv0Jr4W', '0652232802', TO_DATE('1977-11-30', 'YYYY-MM-DD'), '35 rue de la Paix, Strasbourg', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Garcia', 'Julien', 'julien.garcia_17@gmail.com', '$2b$Cv0Jr4W', '0628824093', TO_DATE('1992-04-29', 'YYYY-MM-DD'), '50 boulevard Voltaire, Paris', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Perrin', 'Jade', 'jade.perrin_18@yahoo.com', '$2b$12$i95ZeFRp0Jr4W', '0654768896', TO_DATE('1980-12-15', 'YYYY-MM-DD'), '12 boulevard Voltaire, Strasbourg', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Roux', 'Antoine', 'antoine.roux_19@gmail.com', '$2b$12KzdfxCv0Jr4W', '0675394496', TO_DATE('1989-03-16', 'YYYY-MM-DD'), '91 rue Saint-Denis, Lille', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Vincent', 'Lucie', 'lucie.vincent_20@yahoo.com', '$2b$12$i95ZeFv0Jr4W', '0662528258', TO_DATE('1986-07-03', 'YYYY-MM-DD'), '52 rue du Port, Toulouse', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Benali', 'Romain', 'romain.benali_21@gmail.com', '$2b$12dfxCv0Jr4W', '0684087805', TO_DATE('1986-03-07', 'YYYY-MM-DD'), '37 avenue Montaigne, Paris', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Diallo', 'Clara', 'clara.diallo_22@yahoo.com', '$2b$12$fxCv0Jr4W', '0613670597', TO_DATE('1997-04-04', 'YYYY-MM-DD'), '19 boulevard Haussmann, Bordeaux', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Nguyen', 'Nicolas', 'nicolas.nguyen_23@gmail.com','2XPyps3KzdfxCv0Jr4W', '0678811037', TO_DATE('1981-11-26', 'YYYY-MM-DD'), '46 rue du Port, Nantes', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Zhang', 'Alice', 'alice.zhang_24@yahoo.com', 'fxCv0Jr4W', '0674431020', TO_DATE('1979-12-07', 'YYYY-MM-DD'), '94 rue du Port, Nantes', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Kowalski', 'Alexis', 'alexis.kowalski_25@gmail.com', '$2blmp$i95ZJr4W', '0615309909', TO_DATE('1989-04-20', 'YYYY-MM-DD'), '46 avenue Montaigne, Nice', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Fernandez', 'Zoé', 'zoe.fernandez_26@yahoo.com', '$2bopeg95Z0Jr4W', '0647076802', TO_DATE('1964-07-31', 'YYYY-MM-DD'), '90 rue du Port, Lille', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Muller', 'Baptiste', 'baptiste.muller_27@gmail.com', '$2b$12$ixCv0Jr4W', '0627489691', TO_DATE('1978-06-01', 'YYYY-MM-DD'), '67 avenue Montaigne, Paris', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Rossi', 'Lena', 'lena.rossi_28@yahoo.com', '4ZeB2XPyps3KzdfxCv0Jr4W', '0610316797', TO_DATE('1982-02-06', 'YYYY-MM-DD'), '91 avenue de la République, Nice', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Santos', 'Quentin', 'quentin.santos_29@gmail.com', 'omùKzdfxCv0Jr4W', '0686955644', TO_DATE('1961-11-27', 'YYYY-MM-DD'), '9 rue du Port, Marseille', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Ibrahim', 'Noemie', 'noemie.ibrahim_30@yahoo.com', '$2dfxCv0Jr4W', '0612212422', TO_DATE('1984-01-03', 'YYYY-MM-DD'), '28 avenue Foch, Paris', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Chevalier', 'Pierre', 'pierre.chevalier_31@gmail.com', '$2b$12$i93KzdfxCv0Jr4W', '0677848656', TO_DATE('1963-10-29', 'YYYY-MM-DD'), '18 boulevard Haussmann, Paris', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Robin', 'Amelie', 'amelie.robin_32@yahoo.com', '$2b$12$i95Zps3KzdfxCv0Jr4W', '0646971911', TO_DATE('1974-08-14', 'YYYY-MM-DD'), '65 rue Saint-Denis, Nantes', 'France', 'CLOTURE');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Morel', 'Adrien', 'adrien.morel_33@gmail.com', 'i95ZeFRp3CqbXkaTKzdfxCv0Jr4W', '0655353183', TO_DATE('1997-09-11', 'YYYY-MM-DD'), '92 avenue de la République, Nantes', 'France', 'SUSPENDU');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Faure', 'Laura', 'laura.faure_34@yahoo.com', 'mplkyps3KzdfxCv0Jr4W', '0689460765', TO_DATE('1981-09-10', 'YYYY-MM-DD'), '52 avenue Montaigne, Paris', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Rousseau', 'Guillaume', 'guillaume.rousseau_35@gmail.com', 'dfreZeB2XPyps3KzdfxCv0Jr4W', '0653813376', TO_DATE('1974-03-06', 'YYYY-MM-DD'), '63 rue de la Paix, Nice', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Blanc', 'Pauline', 'pauline.blanc_36@yahoo.com', '$2bJr4W', '0651839240', TO_DATE('1990-01-05', 'YYYY-MM-DD'), '14 avenue Foch, Rennes', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Guerin', 'Raphael', 'raphael.guerin_37@gmail.com', '$2b$lop4W', '0682116566', TO_DATE('1987-10-29', 'YYYY-MM-DD'), '13 boulevard Haussmann, Nice', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Mercier', 'Marion', 'marion.mercier_38@yahoo.com', '$2fxCv0Jr4W', '0675878961', TO_DATE('1977-05-11', 'YYYY-MM-DD'), '80 boulevard Voltaire, Nice', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Boyer', 'Arthur', 'arthur.boyer_39@gmail.com', '$2bdsefxCv0Jr4W', '0695140922', TO_DATE('1999-03-03', 'YYYY-MM-DD'), '32 boulevard Haussmann, Lyon', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Gautier', 'Julie', 'julie.gautier_40@yahoo.com', '$2b$1uikv0Jr4W', '0690683811', TO_DATE('1975-01-31', 'YYYY-MM-DD'), '66 boulevard Voltaire, Paris', 'France', 'SUSPENDU');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Dumont', 'Kevin', 'kevin.dumont_41@gmail.com', 'lofxCv0Jr4W', '0664382210', TO_DATE('1974-10-07', 'YYYY-MM-DD'), '65 rue de la Paix, Marseille', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Lambert', 'Elisa', 'elisa.lambert_42@yahoo.com', '4ZeB2XPyps3KzdfxCv0Jr4W', '0654285170', TO_DATE('1967-05-13', 'YYYY-MM-DD'), '6 avenue Montaigne, Nice', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Fontaine', 'Florian', 'florian.fontaine_43@gmail.com', '$2b$12$isedKzdfxCv0Jr4W', '0674841425', TO_DATE('1987-10-08', 'YYYY-MM-DD'), '55 rue du Port, Marseille', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Renard', 'Anais', 'anais.renard_44@yahoo.com', '$2zdfxCv0Jr4W', '0614627785', TO_DATE('1970-10-24', 'YYYY-MM-DD'), '78 avenue Foch, Strasbourg', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Morin', 'Clement', 'clement.morin_45@gmail.com', 'Pyps3KzdfxCv0Jr4W', '0685644769', TO_DATE('1993-01-14', 'YYYY-MM-DD'), '37 avenue Foch, Paris', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Caron', 'Sarah', 'sarah.caron_46@yahoo.com', '$Q4ZeB2XPyps3KzdfxCv0Jr4W', '0671503154', TO_DATE('1983-05-24', 'YYYY-MM-DD'), '79 boulevard Haussmann, Lyon', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Noel', 'Yann', 'yann.noel_47@gmail.com', '$2b$12$i9yps3KzdfxCv0Jr4W', '0662344757', TO_DATE('1973-03-26', 'YYYY-MM-DD'), '83 rue de la Paix, Lyon', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Marchand', 'Oceane', 'oceane.marchand_48@yahoo.com', '$2b$12$i95ZXPyps3KzdfxCv0Jr4W', '0615009148', TO_DATE('1990-04-15', 'YYYY-MM-DD'), '23 rue du Port, Paris', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Picard', 'Mathieu', 'mathieu.picard_49@gmail.com', '$2b$12$izyQ4ZeB2XPyps3KzdfxCv0Jr4W', '0640989951', TO_DATE('1963-09-13', 'YYYY-MM-DD'), '63 rue Nationale, Paris', 'France', 'ACTIF');
INSERT INTO clients (nom, prenom, email, mot_de_passe, telephone, date_naissance, adresse, pays, statut) VALUES ('Clement', 'Estelle', 'estelle.clement_50@yahoo.com', '$2ps3KzdfxCv0Jr4W', '0656961318', TO_DATE('1995-03-29', 'YYYY-MM-DD'), '62 rue Nationale, Bordeaux', 'France', 'ACTIF');

-- INSERT comptes
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (1, 'FR763000100794123450000100001', 'EPARGNE', 22309.32, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (2, 'FR763000100794123450000200002', 'COURANT', 24454.28, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (2, 'FR763000100794123450000200003', 'COURANT', 27588.92, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (3, 'FR763000100794123450000300004', 'PROFESSIONNEL', 15297.32, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (4, 'FR763000100794123450000400005', 'COURANT', 17733.51, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (5, 'FR763000100794123450000500006', 'PROFESSIONNEL', 47030.25, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (6, 'FR763000100794123450000600007', 'COURANT', 28654.29, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (7, 'FR763000100794123450000700008', 'PROFESSIONNEL', 46187.86, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (8, 'FR763000100794123450000800009', 'EPARGNE', 36916.51, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (8, 'FR763000100794123450000800010', 'EPARGNE', 33682.79, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (9, 'FR763000100794123450000900011', 'PROFESSIONNEL', 3395.04, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (10, 'FR763000100794123450001000012', 'EPARGNE', 13077.13, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (10, 'FR763000100794123450001000013', 'PROFESSIONNEL', 11515.13, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (11, 'FR763000100794123450001100014', 'PROFESSIONNEL', 14530.28, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (12, 'FR763000100794123450001200015', 'COURANT', 42658.31, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (13, 'FR763000100794123450001300016', 'EPARGNE', 32985.15, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (14, 'FR763000100794123450001400017', 'PROFESSIONNEL', 46421.71, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (14, 'FR763000100794123450001400018', 'PROFESSIONNEL', 1894.2, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (15, 'FR763000100794123450001500019', 'COURANT', 9115.2, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (16, 'FR763000100794123450001600020', 'COURANT', 20801.88, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (17, 'FR763000100794123450001700021', 'PROFESSIONNEL', 45197.69, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (17, 'FR763000100794123450001700022', 'EPARGNE', 7524.53, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (18, 'FR763000100794123450001800023', 'EPARGNE', 5885.69, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (19, 'FR763000100794123450001900024', 'EPARGNE', 9321.81, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (20, 'FR763000100794123450002000025', 'COURANT', 13019.9, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (20, 'FR763000100794123450002000026', 'EPARGNE', 34104.56, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (21, 'FR763000100794123450002100027', 'COURANT', 10635.89, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (21, 'FR763000100794123450002100028', 'PROFESSIONNEL', 16405.12, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (22, 'FR763000100794123450002200029', 'EPARGNE', 41067.94, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (22, 'FR763000100794123450002200030', 'EPARGNE', 27453.86, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (23, 'FR763000100794123450002300031', 'PROFESSIONNEL', 16587.14, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (24, 'FR763000100794123450002400032', 'PROFESSIONNEL', 15423.4, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (25, 'FR763000100794123450002500033', 'COURANT', 32433.04, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (25, 'FR763000100794123450002500034', 'COURANT', 42520.19, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (26, 'FR763000100794123450002600035', 'PROFESSIONNEL', 49989.83, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (26, 'FR763000100794123450002600036', 'EPARGNE', 23102.74, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (27, 'FR763000100794123450002700037', 'COURANT', 32636.57, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (27, 'FR763000100794123450002700038', 'EPARGNE', 45043.12, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (28, 'FR763000100794123450002800039', 'EPARGNE', 33066.97, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (28, 'FR763000100794123450002800040', 'COURANT', 38271.77, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (29, 'FR763000100794123450002900041', 'EPARGNE', 3516.45, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (30, 'FR763000100794123450003000042', 'PROFESSIONNEL', 17468.49, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (30, 'FR763000100794123450003000043', 'COURANT', 26280.43, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (31, 'FR763000100794123450003100044', 'PROFESSIONNEL', 37965.6, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (32, 'FR763000100794123450003200045', 'COURANT', 27126.44, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (32, 'FR763000100794123450003200046', 'EPARGNE', 16538.53, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (33, 'FR763000100794123450003300047', 'PROFESSIONNEL', 11562.84, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (34, 'FR763000100794123450003400048', 'COURANT', 18929.84, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (34, 'FR763000100794123450003400049', 'EPARGNE', 18737.25, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (35, 'FR763000100794123450003500050', 'PROFESSIONNEL', 49659.6, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (35, 'FR763000100794123450003500051', 'PROFESSIONNEL', 18315.8, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (36, 'FR763000100794123450003600052', 'EPARGNE', 24598.18, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (36, 'FR763000100794123450003600053', 'PROFESSIONNEL', 43937.78, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (37, 'FR763000100794123450003700054', 'PROFESSIONNEL', 6981.87, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (38, 'FR763000100794123450003800055', 'PROFESSIONNEL', 2479.8, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (38, 'FR763000100794123450003800056', 'EPARGNE', 23552.41, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (39, 'FR763000100794123450003900057', 'EPARGNE', 13277.27, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (39, 'FR763000100794123450003900058', 'COURANT', 44152.17, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (40, 'FR763000100794123450004000059', 'PROFESSIONNEL', 27193.85, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (40, 'FR763000100794123450004000060', 'PROFESSIONNEL', 45017.51, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (41, 'FR763000100794123450004100061', 'COURANT', 39770.59, 'BLOQUE');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (42, 'FR763000100794123450004200062', 'PROFESSIONNEL', 47775.11, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (42, 'FR763000100794123450004200063', 'EPARGNE', 2669.47, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (43, 'FR763000100794123450004300064', 'PROFESSIONNEL', 19156.81, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (44, 'FR763000100794123450004400065', 'COURANT', 40056.71, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (44, 'FR763000100794123450004400066', 'PROFESSIONNEL', 42920.43, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (45, 'FR763000100794123450004500067', 'EPARGNE', 14513.38, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (46, 'FR763000100794123450004600068', 'PROFESSIONNEL', 20133.21, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (46, 'FR763000100794123450004600069', 'COURANT', 19557.36, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (47, 'FR763000100794123450004700070', 'COURANT', 47100.49, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (48, 'FR763000100794123450004800071', 'EPARGNE', 5804.41, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (49, 'FR763000100794123450004900072', 'COURANT', 14130.15, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (49, 'FR763000100794123450004900073', 'EPARGNE', 33411.09, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (50, 'FR763000100794123450005000074', 'EPARGNE', 26926.09, 'ACTIF');
INSERT INTO comptes (client_id, numero_compte, type_compte, solde, statut) VALUES (50, 'FR763000100794123450005000075', 'EPARGNE', 44578.03, 'BLOQUE');

-- INSERT transactions
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (1, 'PAIEMENT_EN_LIGNE', 9866.16, 'France', 'Italie', '10.0.0.10', 'VALIDEE', 23.08);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (1, 'VIREMENT', 6754.6, 'France', 'Allemagne', '192.168.1.45', 'VALIDEE', 3.58);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (2, 'DEPOT', 2516.93, 'France', 'Suisse', '10.0.0.38', 'VALIDEE', 3.75);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (2, 'RETRAIT', 9330.85, 'France', 'Espagne', '192.168.1.1', 'VALIDEE', 21.74);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (2, 'PAIEMENT_EN_LIGNE', 4729.21, 'France', 'Suisse', '192.168.1.28', 'REJETEE', 1.77);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (2, 'VIREMENT', 7361.09, 'France', 'Suisse', '192.168.1.21', 'VALIDEE', 18.15);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (3, 'TRANSACTION_MOBILE', 5561.97, 'France', 'Suisse', '192.168.1.8', 'VALIDEE', 24.59);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (3, 'RETRAIT', 105.01, 'France', 'France', '192.168.1.44', 'VALIDEE', 29.15);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (3, 'RETRAIT', 241.5, 'France', 'Belgique', '192.168.1.17', 'VALIDEE', 7.1);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (3, 'DEPOT', 2167.37, 'France', 'Belgique', '192.168.1.41', 'VALIDEE', 19.66);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (4, 'PAIEMENT_EN_LIGNE', 1394.17, 'France', 'France', '10.0.0.38', 'VALIDEE', 19.49);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (4, 'RETRAIT', 5593.48, 'France', 'Espagne', '192.168.1.15', 'REJETEE', 22.57);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (4, 'VIREMENT', 3478.04, 'France', 'Belgique', '10.0.0.24', 'REJETEE', 16.78);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (4, 'VIREMENT', 14353.11, 'France', 'Chine', '223.5.5.5', 'EN_ANALYSE', 76.44);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (5, 'RETRAIT', 103.31, 'France', 'Allemagne', '192.168.1.16', 'VALIDEE', 23.67);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (5, 'RETRAIT', 9934.73, 'France', 'Suisse', '192.168.1.32', 'REJETEE', 9.64);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (6, 'PAIEMENT_EN_LIGNE', 9396.9, 'France', 'Allemagne', '192.168.1.3', 'REJETEE', 6.17);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (6, 'DEPOT', 3494.94, 'France', 'France', '10.0.0.34', 'VALIDEE', 29.67);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (6, 'RETRAIT', 14991.17, 'France', 'Chine', '223.5.5.5', 'EN_ANALYSE', 87.08);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (7, 'VIREMENT', 4181.88, 'France', 'Suisse', '10.0.0.8', 'VALIDEE', 19.49);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (7, 'RETRAIT', 7553.46, 'France', 'France', '10.0.0.19', 'VALIDEE', 25.65);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (7, 'DEPOT', 5163.49, 'France', 'Italie', '192.168.1.34', 'VALIDEE', 3.14);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (7, 'PAIEMENT_EN_LIGNE', 5606.66, 'France', 'France', '192.168.1.42', 'VALIDEE', 17.13);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (8, 'TRANSACTION_MOBILE', 8348.93, 'France', 'Allemagne', '10.0.0.3', 'VALIDEE', 6.86);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (8, 'PAIEMENT_EN_LIGNE', 687.88, 'France', 'Espagne', '192.168.1.4', 'VALIDEE', 25.16);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (8, 'VIREMENT', 3992.55, 'France', 'France', '192.168.1.6', 'VALIDEE', 27.48);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (8, 'PAIEMENT_EN_LIGNE', 9424.31, 'France', 'France', '192.168.1.2', 'REJETEE', 17.09);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (9, 'RETRAIT', 5812.87, 'France', 'Chine', '194.165.16.1', 'EN_ANALYSE', 86.03);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (9, 'TRANSACTION_MOBILE', 8435.42, 'France', 'Suisse', '192.168.1.42', 'VALIDEE', 12.28);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (10, 'VIREMENT', 7100.89, 'France', 'Ukraine', '197.210.55.3', 'EN_ANALYSE', 90.58);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (10, 'PAIEMENT_EN_LIGNE', 99.45, 'France', 'Allemagne', '192.168.1.20', 'VALIDEE', 6.93);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (10, 'VIREMENT', 9338.41, 'France', 'France', '10.0.0.20', 'REJETEE', 16.65);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (10, 'DEPOT', 5720.54, 'France', 'Espagne', '10.0.0.32', 'VALIDEE', 7.48);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (11, 'DEPOT', 9972.93, 'France', 'France', '10.0.0.19', 'VALIDEE', 11.76);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (11, 'DEPOT', 4202.92, 'France', 'Italie', '10.0.0.8', 'VALIDEE', 20.82);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (11, 'DEPOT', 4947.78, 'France', 'Belgique', '10.0.0.5', 'VALIDEE', 26.96);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (11, 'VIREMENT', 1578.21, 'France', 'Belgique', '192.168.1.42', 'REJETEE', 29.9);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (12, 'VIREMENT', 257.29, 'France', 'Belgique', '192.168.1.29', 'VALIDEE', 21.11);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (12, 'DEPOT', 5927.21, 'France', 'Italie', '192.168.1.40', 'VALIDEE', 10.71);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (12, 'DEPOT', 9685.4, 'France', 'Espagne', '10.0.0.17', 'VALIDEE', 19.12);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (13, 'DEPOT', 512.78, 'France', 'Espagne', '192.168.1.13', 'VALIDEE', 19.35);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (13, 'PAIEMENT_EN_LIGNE', 8202.76, 'France', 'France', '10.0.0.49', 'VALIDEE', 22.08);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (13, 'PAIEMENT_EN_LIGNE', 7516.84, 'France', 'Italie', '10.0.0.11', 'VALIDEE', 5.82);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (14, 'TRANSACTION_MOBILE', 2778.31, 'France', 'Suisse', '10.0.0.37', 'VALIDEE', 21.22);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (14, 'PAIEMENT_EN_LIGNE', 465.25, 'France', 'Suisse', '192.168.1.5', 'VALIDEE', 24.6);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (14, 'RETRAIT', 378.65, 'France', 'Suisse', '10.0.0.21', 'VALIDEE', 16.34);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (15, 'DEPOT', 2462.19, 'France', 'Italie', '192.168.1.5', 'VALIDEE', 3.33);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (15, 'DEPOT', 3449.38, 'France', 'Allemagne', '192.168.1.36', 'VALIDEE', 20.42);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (15, 'VIREMENT', 4616.82, 'France', 'Suisse', '10.0.0.4', 'VALIDEE', 8.09);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (16, 'TRANSACTION_MOBILE', 2445.58, 'France', 'Espagne', '192.168.1.30', 'REJETEE', 21.7);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (16, 'PAIEMENT_EN_LIGNE', 4582.59, 'France', 'Espagne', '10.0.0.10', 'VALIDEE', 1.6);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (16, 'PAIEMENT_EN_LIGNE', 2146.28, 'France', 'Italie', '192.168.1.37', 'VALIDEE', 16.61);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (16, 'PAIEMENT_EN_LIGNE', 10172.98, 'France', 'Iran', '194.165.16.1', 'EN_ANALYSE', 93.74);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (17, 'PAIEMENT_EN_LIGNE', 8857.84, 'France', 'Belgique', '10.0.0.11', 'VALIDEE', 29.8);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (17, 'TRANSACTION_MOBILE', 12.27, 'France', 'Italie', '192.168.1.26', 'VALIDEE', 23.46);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (17, 'TRANSACTION_MOBILE', 6331.39, 'France', 'Espagne', '192.168.1.10', 'VALIDEE', 12.5);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (17, 'RETRAIT', 3124.23, 'France', 'Allemagne', '192.168.1.34', 'VALIDEE', 9.63);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (18, 'TRANSACTION_MOBILE', 2982.19, 'France', 'Espagne', '192.168.1.22', 'VALIDEE', 3.62);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (18, 'VIREMENT', 2892.06, 'France', 'Allemagne', '10.0.0.26', 'REJETEE', 5.84);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (18, 'PAIEMENT_EN_LIGNE', 7169.89, 'France', 'France', '192.168.1.26', 'VALIDEE', 26.22);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (19, 'VIREMENT', 848.06, 'France', 'Belgique', '10.0.0.23', 'VALIDEE', 23.25);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (19, 'PAIEMENT_EN_LIGNE', 944.81, 'France', 'Espagne', '192.168.1.37', 'VALIDEE', 26.9);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (19, 'VIREMENT', 8771.15, 'France', 'Italie', '10.0.0.14', 'VALIDEE', 17.49);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (20, 'RETRAIT', 8198.03, 'France', 'Espagne', '10.0.0.40', 'VALIDEE', 9.71);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (20, 'VIREMENT', 546.51, 'France', 'Espagne', '10.0.0.32', 'VALIDEE', 27.83);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (21, 'RETRAIT', 514.57, 'France', 'Espagne', '10.0.0.25', 'VALIDEE', 13.05);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (21, 'DEPOT', 392.34, 'France', 'Suisse', '10.0.0.40', 'VALIDEE', 10.09);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (21, 'DEPOT', 6484.0, 'France', 'Chine', '223.5.5.5', 'EN_ANALYSE', 98.65);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (22, 'RETRAIT', 7631.78, 'France', 'Chine', '185.220.101.5', 'EN_ANALYSE', 75.89);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (22, 'DEPOT', 2597.88, 'France', 'France', '10.0.0.49', 'REJETEE', 19.73);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (22, 'DEPOT', 2225.61, 'France', 'Allemagne', '192.168.1.8', 'VALIDEE', 1.86);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (22, 'VIREMENT', 1417.6, 'France', 'Italie', '192.168.1.33', 'VALIDEE', 1.94);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (23, 'DEPOT', 9704.66, 'France', 'Espagne', '10.0.0.26', 'VALIDEE', 21.48);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (23, 'TRANSACTION_MOBILE', 4657.75, 'France', 'Corée du Nord', '185.220.101.5', 'EN_ANALYSE', 82.46);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (23, 'RETRAIT', 4259.53, 'France', 'Iran', '185.220.101.5', 'EN_ANALYSE', 96.48);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (23, 'RETRAIT', 13930.29, 'France', 'Russie', '197.210.55.3', 'EN_ANALYSE', 71.11);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (24, 'TRANSACTION_MOBILE', 8278.53, 'France', 'Espagne', '192.168.1.15', 'VALIDEE', 20.02);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (24, 'PAIEMENT_EN_LIGNE', 6382.29, 'France', 'Allemagne', '192.168.1.26', 'VALIDEE', 8.82);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (24, 'PAIEMENT_EN_LIGNE', 8652.06, 'France', 'Suisse', '10.0.0.32', 'VALIDEE', 23.41);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (25, 'DEPOT', 4078.8, 'France', 'France', '192.168.1.13', 'VALIDEE', 23.12);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (25, 'TRANSACTION_MOBILE', 7637.93, 'France', 'Italie', '10.0.0.37', 'VALIDEE', 21.71);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (25, 'TRANSACTION_MOBILE', 9076.36, 'France', 'Italie', '192.168.1.7', 'REJETEE', 14.68);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (26, 'RETRAIT', 4115.91, 'France', 'Espagne', '10.0.0.27', 'REJETEE', 21.1);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (26, 'VIREMENT', 2734.64, 'France', 'Belgique', '192.168.1.15', 'REJETEE', 1.33);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (27, 'TRANSACTION_MOBILE', 8198.93, 'France', 'Italie', '192.168.1.42', 'VALIDEE', 19.86);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (27, 'PAIEMENT_EN_LIGNE', 9119.92, 'France', 'Suisse', '10.0.0.27', 'REJETEE', 8.92);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (27, 'VIREMENT', 166.41, 'France', 'Belgique', '10.0.0.48', 'VALIDEE', 23.7);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (27, 'PAIEMENT_EN_LIGNE', 660.9, 'France', 'Allemagne', '10.0.0.6', 'VALIDEE', 25.62);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (28, 'PAIEMENT_EN_LIGNE', 4156.37, 'France', 'Allemagne', '10.0.0.43', 'REJETEE', 17.73);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (28, 'DEPOT', 9160.49, 'France', 'Espagne', '10.0.0.33', 'VALIDEE', 11.58);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (28, 'PAIEMENT_EN_LIGNE', 1208.75, 'France', 'Espagne', '192.168.1.39', 'VALIDEE', 22.61);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (29, 'TRANSACTION_MOBILE', 4260.5, 'France', 'France', '192.168.1.20', 'VALIDEE', 26.18);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (29, 'RETRAIT', 8164.02, 'France', 'Belgique', '192.168.1.46', 'VALIDEE', 27.46);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (29, 'TRANSACTION_MOBILE', 7854.45, 'France', 'Suisse', '10.0.0.49', 'VALIDEE', 4.08);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (30, 'VIREMENT', 3063.61, 'France', 'Italie', '192.168.1.33', 'VALIDEE', 22.28);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (30, 'DEPOT', 518.43, 'France', 'France', '192.168.1.31', 'VALIDEE', 15.22);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (31, 'PAIEMENT_EN_LIGNE', 4049.38, 'France', 'Italie', '10.0.0.21', 'VALIDEE', 12.52);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (31, 'RETRAIT', 841.66, 'France', 'Allemagne', '10.0.0.8', 'VALIDEE', 14.26);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (32, 'DEPOT', 1391.39, 'France', 'Allemagne', '10.0.0.26', 'VALIDEE', 25.37);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (32, 'RETRAIT', 12702.97, 'France', 'Russie', '223.5.5.5', 'EN_ANALYSE', 83.92);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (33, 'TRANSACTION_MOBILE', 4830.66, 'France', 'Belgique', '192.168.1.25', 'VALIDEE', 14.06);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (33, 'PAIEMENT_EN_LIGNE', 7090.58, 'France', 'France', '10.0.0.4', 'REJETEE', 23.88);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (34, 'RETRAIT', 1630.66, 'France', 'Suisse', '10.0.0.11', 'REJETEE', 20.1);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (34, 'RETRAIT', 4799.93, 'France', 'Belgique', '192.168.1.44', 'REJETEE', 29.88);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (34, 'PAIEMENT_EN_LIGNE', 2310.63, 'France', 'France', '10.0.0.19', 'VALIDEE', 12.44);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (34, 'RETRAIT', 6324.66, 'France', 'Italie', '10.0.0.3', 'VALIDEE', 14.64);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (35, 'TRANSACTION_MOBILE', 8519.59, 'France', 'Allemagne', '10.0.0.17', 'VALIDEE', 17.82);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (35, 'VIREMENT', 5931.89, 'France', 'Corée du Nord', '185.220.101.5', 'EN_ANALYSE', 76.72);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (36, 'DEPOT', 5546.85, 'France', 'Allemagne', '192.168.1.17', 'VALIDEE', 28.54);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (36, 'VIREMENT', 5327.45, 'France', 'Suisse', '192.168.1.43', 'REJETEE', 12.02);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (36, 'DEPOT', 355.17, 'France', 'Suisse', '192.168.1.4', 'VALIDEE', 9.43);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (37, 'TRANSACTION_MOBILE', 7838.97, 'France', 'Espagne', '192.168.1.6', 'VALIDEE', 5.39);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (37, 'DEPOT', 3243.82, 'France', 'Espagne', '192.168.1.26', 'VALIDEE', 10.32);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (37, 'DEPOT', 4135.53, 'France', 'Belgique', '10.0.0.22', 'VALIDEE', 19.7);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (38, 'TRANSACTION_MOBILE', 2666.76, 'France', 'Espagne', '192.168.1.14', 'REJETEE', 3.57);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (38, 'TRANSACTION_MOBILE', 14325.24, 'France', 'Nigeria', '91.108.4.1', 'EN_ANALYSE', 70.36);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (38, 'PAIEMENT_EN_LIGNE', 11292.56, 'France', 'Ukraine', '223.5.5.5', 'EN_ANALYSE', 94.53);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (38, 'TRANSACTION_MOBILE', 1691.86, 'France', 'Italie', '192.168.1.2', 'VALIDEE', 8.26);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (39, 'VIREMENT', 3291.11, 'France', 'Italie', '192.168.1.8', 'VALIDEE', 16.28);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (39, 'RETRAIT', 4671.94, 'France', 'Allemagne', '192.168.1.16', 'VALIDEE', 1.04);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (39, 'RETRAIT', 1841.68, 'France', 'Belgique', '10.0.0.41', 'VALIDEE', 3.05);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (40, 'RETRAIT', 3493.28, 'France', 'France', '192.168.1.30', 'VALIDEE', 3.32);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (40, 'RETRAIT', 596.72, 'France', 'Suisse', '192.168.1.5', 'REJETEE', 1.05);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (40, 'PAIEMENT_EN_LIGNE', 5073.62, 'France', 'Allemagne', '10.0.0.10', 'VALIDEE', 29.84);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (41, 'TRANSACTION_MOBILE', 7673.21, 'France', 'Allemagne', '10.0.0.18', 'REJETEE', 23.17);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (41, 'TRANSACTION_MOBILE', 147.15, 'France', 'Espagne', '10.0.0.19', 'REJETEE', 20.65);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (42, 'DEPOT', 478.09, 'France', 'Allemagne', '10.0.0.48', 'REJETEE', 14.77);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (42, 'VIREMENT', 2525.23, 'France', 'Allemagne', '192.168.1.30', 'VALIDEE', 15.43);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (42, 'TRANSACTION_MOBILE', 1838.16, 'France', 'Suisse', '192.168.1.16', 'REJETEE', 9.24);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (43, 'VIREMENT', 9707.79, 'France', 'Allemagne', '192.168.1.40', 'REJETEE', 1.89);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (43, 'DEPOT', 8171.42, 'France', 'France', '192.168.1.34', 'VALIDEE', 29.99);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (43, 'VIREMENT', 1083.82, 'France', 'France', '10.0.0.42', 'VALIDEE', 28.73);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (44, 'RETRAIT', 12954.06, 'France', 'Nigeria', '194.165.16.1', 'EN_ANALYSE', 85.44);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (44, 'RETRAIT', 3225.6, 'France', 'France', '10.0.0.21', 'VALIDEE', 12.95);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (45, 'PAIEMENT_EN_LIGNE', 4161.89, 'France', 'Nigeria', '91.108.4.1', 'EN_ANALYSE', 71.04);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (45, 'DEPOT', 3928.75, 'France', 'Suisse', '10.0.0.31', 'VALIDEE', 7.62);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (45, 'RETRAIT', 2616.22, 'France', 'Italie', '10.0.0.44', 'REJETEE', 5.07);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (45, 'DEPOT', 3300.33, 'France', 'France', '192.168.1.15', 'VALIDEE', 2.0);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (46, 'VIREMENT', 5163.97, 'France', 'Belgique', '192.168.1.34', 'VALIDEE', 19.5);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (46, 'VIREMENT', 9737.06, 'France', 'Italie', '192.168.1.41', 'VALIDEE', 27.93);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (46, 'TRANSACTION_MOBILE', 7526.07, 'France', 'Espagne', '192.168.1.2', 'VALIDEE', 29.58);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (47, 'RETRAIT', 8235.18, 'France', 'Italie', '192.168.1.31', 'VALIDEE', 1.47);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (47, 'TRANSACTION_MOBILE', 8530.97, 'France', 'Suisse', '192.168.1.13', 'VALIDEE', 3.69);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (47, 'TRANSACTION_MOBILE', 3579.35, 'France', 'France', '192.168.1.47', 'VALIDEE', 25.35);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (48, 'RETRAIT', 9530.22, 'France', 'Italie', '10.0.0.28', 'VALIDEE', 7.44);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (48, 'RETRAIT', 6165.08, 'France', 'Belgique', '10.0.0.40', 'VALIDEE', 2.77);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (48, 'RETRAIT', 8844.41, 'France', 'Allemagne', '192.168.1.13', 'VALIDEE', 29.28);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (48, 'TRANSACTION_MOBILE', 3678.17, 'France', 'Italie', '10.0.0.49', 'VALIDEE', 14.67);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (49, 'VIREMENT', 9149.24, 'France', 'Italie', '192.168.1.26', 'REJETEE', 22.49);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (49, 'DEPOT', 1544.5, 'France', 'Allemagne', '192.168.1.44', 'VALIDEE', 4.02);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (49, 'DEPOT', 3212.21, 'France', 'Allemagne', '192.168.1.13', 'VALIDEE', 10.77);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (49, 'DEPOT', 789.91, 'France', 'Allemagne', '10.0.0.14', 'VALIDEE', 27.09);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (50, 'DEPOT', 9574.13, 'France', 'Belgique', '10.0.0.44', 'REJETEE', 21.0);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (50, 'RETRAIT', 7045.51, 'France', 'France', '192.168.1.26', 'VALIDEE', 10.4);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (50, 'PAIEMENT_EN_LIGNE', 7781.71, 'France', 'Espagne', '192.168.1.9', 'VALIDEE', 25.13);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (50, 'RETRAIT', 8702.23, 'France', 'Suisse', '10.0.0.46', 'VALIDEE', 27.08);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (51, 'RETRAIT', 5568.75, 'France', 'France', '10.0.0.35', 'VALIDEE', 16.76);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (51, 'VIREMENT', 5653.85, 'France', 'Iran', '197.210.55.3', 'EN_ANALYSE', 76.44);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (51, 'PAIEMENT_EN_LIGNE', 8668.58, 'France', 'Corée du Nord', '223.5.5.5', 'EN_ANALYSE', 82.29);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (52, 'DEPOT', 9155.22, 'France', 'Belgique', '10.0.0.38', 'VALIDEE', 16.2);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (52, 'VIREMENT', 8372.53, 'France', 'Espagne', '10.0.0.41', 'VALIDEE', 24.68);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (52, 'VIREMENT', 4733.81, 'France', 'Allemagne', '192.168.1.34', 'VALIDEE', 16.99);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (53, 'RETRAIT', 5716.71, 'France', 'Chine', '91.108.4.1', 'EN_ANALYSE', 97.31);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (53, 'RETRAIT', 5859.67, 'France', 'France', '10.0.0.33', 'VALIDEE', 8.69);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (53, 'PAIEMENT_EN_LIGNE', 5386.71, 'France', 'Belgique', '192.168.1.11', 'VALIDEE', 7.25);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (54, 'DEPOT', 9556.87, 'France', 'Allemagne', '10.0.0.39', 'VALIDEE', 22.16);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (54, 'VIREMENT', 3714.29, 'France', 'Belgique', '192.168.1.40', 'REJETEE', 20.49);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (54, 'TRANSACTION_MOBILE', 4702.15, 'France', 'Belgique', '192.168.1.11', 'VALIDEE', 29.27);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (55, 'DEPOT', 6323.32, 'France', 'Allemagne', '192.168.1.33', 'VALIDEE', 25.62);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (55, 'VIREMENT', 7615.93, 'France', 'Belgique', '192.168.1.23', 'VALIDEE', 12.54);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (55, 'RETRAIT', 7149.37, 'France', 'Italie', '10.0.0.8', 'REJETEE', 29.42);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (55, 'PAIEMENT_EN_LIGNE', 2303.86, 'France', 'Espagne', '192.168.1.4', 'VALIDEE', 22.5);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (56, 'DEPOT', 1557.19, 'France', 'France', '192.168.1.25', 'VALIDEE', 19.1);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (56, 'RETRAIT', 498.26, 'France', 'Italie', '10.0.0.3', 'VALIDEE', 21.49);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (56, 'VIREMENT', 8353.47, 'France', 'France', '192.168.1.35', 'VALIDEE', 21.89);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (56, 'VIREMENT', 6175.17, 'France', 'Italie', '10.0.0.30', 'REJETEE', 19.31);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (57, 'DEPOT', 8463.74, 'France', 'Suisse', '10.0.0.30', 'VALIDEE', 20.31);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (57, 'VIREMENT', 3920.56, 'France', 'Suisse', '10.0.0.2', 'VALIDEE', 25.19);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (58, 'RETRAIT', 14613.87, 'France', 'Ukraine', '223.5.5.5', 'EN_ANALYSE', 73.55);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (58, 'DEPOT', 14944.5, 'France', 'Chine', '194.165.16.1', 'EN_ANALYSE', 90.99);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (58, 'VIREMENT', 1801.48, 'France', 'France', '10.0.0.3', 'VALIDEE', 28.19);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (58, 'TRANSACTION_MOBILE', 5396.32, 'France', 'Chine', '185.220.101.5', 'EN_ANALYSE', 71.48);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (59, 'RETRAIT', 6334.04, 'France', 'Espagne', '192.168.1.48', 'VALIDEE', 22.62);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (59, 'VIREMENT', 5214.55, 'France', 'Italie', '10.0.0.24', 'REJETEE', 28.49);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (59, 'VIREMENT', 7415.07, 'France', 'Italie', '192.168.1.8', 'VALIDEE', 3.16);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (60, 'RETRAIT', 9536.8, 'France', 'Allemagne', '192.168.1.35', 'REJETEE', 5.07);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (60, 'TRANSACTION_MOBILE', 4890.5, 'France', 'France', '10.0.0.34', 'REJETEE', 10.24);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (60, 'RETRAIT', 6822.57, 'France', 'Italie', '192.168.1.21', 'VALIDEE', 17.0);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (60, 'DEPOT', 3253.24, 'France', 'Belgique', '10.0.0.15', 'VALIDEE', 10.33);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (61, 'DEPOT', 9898.75, 'France', 'Suisse', '192.168.1.31', 'REJETEE', 18.75);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (61, 'DEPOT', 8455.17, 'France', 'Belgique', '10.0.0.37', 'REJETEE', 12.01);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (62, 'TRANSACTION_MOBILE', 3870.79, 'France', 'Ukraine', '197.210.55.3', 'EN_ANALYSE', 88.13);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (62, 'DEPOT', 6799.05, 'France', 'Suisse', '10.0.0.13', 'VALIDEE', 2.36);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (62, 'DEPOT', 8609.57, 'France', 'Espagne', '10.0.0.46', 'VALIDEE', 18.06);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (62, 'DEPOT', 7426.52, 'France', 'Espagne', '192.168.1.27', 'VALIDEE', 24.24);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (63, 'PAIEMENT_EN_LIGNE', 6840.33, 'France', 'Allemagne', '10.0.0.31', 'VALIDEE', 16.51);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (63, 'PAIEMENT_EN_LIGNE', 5162.75, 'France', 'Allemagne', '192.168.1.33', 'VALIDEE', 22.89);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (63, 'RETRAIT', 7550.04, 'France', 'Belgique', '192.168.1.45', 'VALIDEE', 21.73);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (64, 'VIREMENT', 642.31, 'France', 'Suisse', '10.0.0.43', 'VALIDEE', 22.2);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (64, 'RETRAIT', 1164.24, 'France', 'France', '192.168.1.25', 'VALIDEE', 6.03);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (65, 'DEPOT', 425.4, 'France', 'Italie', '10.0.0.33', 'REJETEE', 20.86);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (65, 'DEPOT', 911.82, 'France', 'Espagne', '10.0.0.4', 'REJETEE', 6.35);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (66, 'VIREMENT', 3186.78, 'France', 'Suisse', '192.168.1.22', 'VALIDEE', 19.02);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (66, 'RETRAIT', 5041.95, 'France', 'Espagne', '192.168.1.11', 'VALIDEE', 13.83);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (66, 'TRANSACTION_MOBILE', 9415.72, 'France', 'Allemagne', '10.0.0.29', 'REJETEE', 10.38);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (66, 'PAIEMENT_EN_LIGNE', 13344.4, 'France', 'Russie', '197.210.55.3', 'EN_ANALYSE', 88.52);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (67, 'PAIEMENT_EN_LIGNE', 322.31, 'France', 'Belgique', '192.168.1.45', 'VALIDEE', 24.75);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (67, 'RETRAIT', 9455.87, 'France', 'France', '192.168.1.37', 'VALIDEE', 19.88);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (67, 'TRANSACTION_MOBILE', 6403.11, 'France', 'Belgique', '192.168.1.10', 'VALIDEE', 2.82);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (67, 'PAIEMENT_EN_LIGNE', 5553.94, 'France', 'Espagne', '192.168.1.15', 'VALIDEE', 6.33);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (68, 'RETRAIT', 1065.56, 'France', 'Espagne', '192.168.1.2', 'REJETEE', 13.79);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (68, 'RETRAIT', 433.13, 'France', 'France', '192.168.1.25', 'VALIDEE', 5.2);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (68, 'PAIEMENT_EN_LIGNE', 4509.65, 'France', 'Allemagne', '10.0.0.28', 'VALIDEE', 16.81);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (68, 'RETRAIT', 5465.73, 'France', 'Italie', '192.168.1.42', 'VALIDEE', 15.07);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (69, 'DEPOT', 4422.24, 'France', 'Ukraine', '185.220.101.5', 'EN_ANALYSE', 80.14);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (69, 'DEPOT', 9324.59, 'France', 'Allemagne', '10.0.0.33', 'VALIDEE', 26.11);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (69, 'VIREMENT', 1926.73, 'France', 'Suisse', '192.168.1.6', 'VALIDEE', 14.57);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (69, 'VIREMENT', 10979.23, 'France', 'Russie', '194.165.16.1', 'EN_ANALYSE', 92.27);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (70, 'PAIEMENT_EN_LIGNE', 352.49, 'France', 'Belgique', '10.0.0.20', 'VALIDEE', 14.62);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (70, 'RETRAIT', 5569.35, 'France', 'Italie', '192.168.1.39', 'REJETEE', 16.04);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (70, 'DEPOT', 2323.96, 'France', 'Suisse', '10.0.0.25', 'VALIDEE', 3.29);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (71, 'VIREMENT', 2723.51, 'France', 'Espagne', '192.168.1.19', 'VALIDEE', 5.93);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (71, 'VIREMENT', 6811.15, 'France', 'Italie', '192.168.1.21', 'VALIDEE', 12.22);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (72, 'VIREMENT', 4917.05, 'France', 'Italie', '10.0.0.4', 'VALIDEE', 5.21);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (72, 'RETRAIT', 5028.2, 'France', 'Nigeria', '194.165.16.1', 'EN_ANALYSE', 95.74);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (73, 'DEPOT', 4696.28, 'France', 'France', '10.0.0.41', 'VALIDEE', 26.47);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (73, 'PAIEMENT_EN_LIGNE', 5828.45, 'France', 'Allemagne', '192.168.1.43', 'VALIDEE', 23.97);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (73, 'RETRAIT', 4184.07, 'France', 'France', '192.168.1.8', 'REJETEE', 9.68);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (73, 'DEPOT', 5143.97, 'France', 'Espagne', '10.0.0.47', 'VALIDEE', 12.27);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (74, 'TRANSACTION_MOBILE', 13439.82, 'France', 'Russie', '91.108.4.1', 'EN_ANALYSE', 94.68);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (74, 'PAIEMENT_EN_LIGNE', 1957.32, 'France', 'Espagne', '10.0.0.26', 'VALIDEE', 10.61);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (74, 'DEPOT', 8335.22, 'France', 'Suisse', '10.0.0.10', 'VALIDEE', 7.16);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (74, 'VIREMENT', 8535.99, 'France', 'France', '10.0.0.8', 'VALIDEE', 9.88);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (75, 'RETRAIT', 889.16, 'France', 'Italie', '192.168.1.5', 'VALIDEE', 2.34);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (75, 'TRANSACTION_MOBILE', 7112.88, 'France', 'Italie', '10.0.0.29', 'VALIDEE', 22.59);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (75, 'DEPOT', 14643.73, 'France', 'Chine', '194.165.16.1', 'EN_ANALYSE', 86.3);
INSERT INTO transactions (compte_id, type_transaction, montant, pays_origine, pays_destination, ip_adresse, statut, score_risque) VALUES (75, 'PAIEMENT_EN_LIGNE', 2741.69, 'France', 'Allemagne', '10.0.0.42', 'VALIDEE', 4.05);

-- INSERT fraud
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (14, 'TRANSACTION_INHABITUELLE', 'MOYEN', 74.72, 'EN_COURS', 'ANALYSTE_02', 'Tentative de phishing identifiée.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (19, 'ACCES_NON_AUTORISE', 'MOYEN', 76.24, 'CONFIRME', 'ANALYSTE_02', 'Montant anormalement élevé détecté par le modèle ML.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (28, 'AUTRE', 'ELEVE', 72.73, 'CONFIRME', 'ANALYSTE_02', 'Montant anormalement élevé détecté par le modèle ML.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (30, 'PHISHING', 'MOYEN', 65.72, 'EN_COURS', 'ANALYSTE_01', 'Comportement atypique par rapport à l'historique client.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (53, 'AUTRE', 'CRITIQUE', 97.9, 'EN_COURS', 'ANALYSTE_02', 'Comportement atypique par rapport à l'historique client.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (68, 'USURPATION_IDENTITE', 'MOYEN', 75.49, 'EN_COURS', 'ANALYSTE_01', 'Accès non autorisé détecté sur le compte.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (69, 'AUTRE', 'CRITIQUE', 97.77, 'EN_COURS', 'ANALYSTE_01', 'Tentative de phishing identifiée.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (74, 'ACCES_NON_AUTORISE', 'CRITIQUE', 73.47, 'EN_COURS', 'ANALYSTE_01', 'Accès non autorisé détecté sur le compte.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (75, 'PHISHING', 'MOYEN', 67.9, 'EN_COURS', 'ANALYSTE_03', 'Virement inhabituel vers pays à risque élevé.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (76, 'ACCES_NON_AUTORISE', 'MOYEN', 77.25, 'EN_COURS', 'ANALYSTE_02', 'Comportement atypique par rapport à l'historique client.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (100, 'PHISHING', 'ELEVE', 68.28, 'FAUX_POSITIF', 'ANALYSTE_03', 'Comportement atypique par rapport à l'historique client.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (108, 'USURPATION_IDENTITE', 'ELEVE', 94.73, 'EN_COURS', 'ANALYSTE_01', 'Connexion depuis IP suspecte, pays inhabituel.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (116, 'AUTRE', 'ELEVE', 98.84, 'FAUX_POSITIF', 'ANALYSTE_02', 'Comportement atypique par rapport à l'historique client.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (117, 'AUTRE', 'CRITIQUE', 94.81, 'EN_COURS', 'ANALYSTE_01', 'Comportement atypique par rapport à l'historique client.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (133, 'USURPATION_IDENTITE', 'ELEVE', 87.68, 'CONFIRME', 'ANALYSTE_03', 'Transaction mobile suspecte depuis l'étranger.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (135, 'ACCES_NON_AUTORISE', 'MOYEN', 75.2, 'CONFIRME', 'ANALYSTE_02', 'Transaction mobile suspecte depuis l'étranger.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (158, 'TRANSACTION_INHABITUELLE', 'CRITIQUE', 91.75, 'CONFIRME', 'ANALYSTE_02', 'Transaction mobile suspecte depuis l'étranger.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (159, 'PHISHING', 'ELEVE', 66.42, 'CONFIRME', 'ANALYSTE_01', 'Comportement atypique par rapport à l'historique client.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (163, 'ACCES_NON_AUTORISE', 'ELEVE', 93.02, 'EN_COURS', 'ANALYSTE_03', 'Virement inhabituel vers pays à risque élevé.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (179, 'USURPATION_IDENTITE', 'CRITIQUE', 77.0, 'FAUX_POSITIF', 'ANALYSTE_03', 'Montant anormalement élevé détecté par le modèle ML.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (180, 'ACCES_NON_AUTORISE', 'MOYEN', 74.89, 'CONFIRME', 'ANALYSTE_01', 'Accès non autorisé détecté sur le compte.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (182, 'PHISHING', 'MOYEN', 89.04, 'EN_COURS', 'ANALYSTE_02', 'Tentative de phishing identifiée.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (192, 'ACCES_NON_AUTORISE', 'CRITIQUE', 65.02, 'EN_COURS', 'ANALYSTE_01', 'Connexion depuis IP suspecte, pays inhabituel.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (206, 'AUTRE', 'ELEVE', 78.88, 'FAUX_POSITIF', 'ANALYSTE_01', 'Comportement atypique par rapport à l'historique client.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (215, 'AUTRE', 'ELEVE', 98.7, 'CONFIRME', 'ANALYSTE_03', 'Accès non autorisé détecté sur le compte.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (218, 'PHISHING', 'ELEVE', 77.5, 'EN_COURS', 'ANALYSTE_02', 'Transaction mobile suspecte depuis l'étranger.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (225, 'USURPATION_IDENTITE', 'ELEVE', 88.49, 'EN_COURS', 'ANALYSTE_01', 'Virement inhabituel vers pays à risque élevé.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (230, 'ACCES_NON_AUTORISE', 'MOYEN', 87.93, 'CONFIRME', 'ANALYSTE_02', 'Tentative de phishing identifiée.');
INSERT INTO fraud (transaction_id, type_fraude, niveau_risque, score_ml, statut_analyse, analyste_id, commentaire) VALUES (236, 'ACCES_NON_AUTORISE', 'MOYEN', 88.39, 'EN_COURS', 'ANALYSTE_03', 'Tentative de phishing identifiée.');

COMMIT;

-- Vérification
SELECT 'clients' AS table_name, COUNT(*) AS nb FROM clients UNION ALL
SELECT 'comptes', COUNT(*) FROM comptes UNION ALL
SELECT 'transactions', COUNT(*) FROM transactions UNION ALL
SELECT 'fraud', COUNT(*) FROM fraud;